[package]
name = "asteroid"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }
rand = { version = "0.8", features = ["small_rng"] }
rfd = "0.13"
